#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_topmost off \
	window_shadow off \
    window_opacity on \
	window_animation_duration 0.05 \
	window_opacity_duration 0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.7 \
	insert_feedback_color 0x00d75f5f \
	active_window_border_color 0x80565f89 \
	normal_window_border_color 0x80565f89 \
	window_border_width 1 \
	window_border_radius 12 \
	window_border_blur on \
	window_border_hidpi on \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 15 \
	bottom_padding 15 \
	left_padding 15 \
	right_padding 15 \
	window_gap 15 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:25:0

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="Stats" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
#yabai -m rule --add app="^Finder$" sticky=on manage=off
#yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
#yabai -m rule --add app="Pomotroid" manage=off
#yabai -m rule --add app="Anki" opacity=0.90
#yabai -m rule --add app="Raycast" sticky=on manage=off
yabai -m rule --add app="Stickies" sticky=off manage=off
ode


echo "yabai configuration loaded.."
