#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#test
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_topmost off \
	window_shadow off \
    window_opacity on \
	window_animation_duration 0.333 \
	window_opacity_duration 0.333 \
	active_window_opacity 1 \
	normal_window_opacity 0.44 \
	insert_feedback_color 0x00d75f5f \
	active_window_border_color 0xff179299 \
	normal_window_border_color 0xff4db6ac \
	window_border_width 3 \
	window_border_radius 11 \
	window_border_blur on \
	window_border_hidpi on \
	window_border off \
	split_ratio 0.50 \
	split_type auto \
	auto_balance on \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 8 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:35:0

yabai -m rule --add app="^(LuLu|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App StoreAlfred|Activity Monitor)$" manage=off
yabai -m rule --add app="Stats" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=off manage=off
#yabai -m rule --add app="^Finder$" sticky=on manage=off
#yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=yes manage=yes
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
#yabai -m rule --add app="Pomotroid" manage=off
#yabai -m rule --add app="Anki" opacity=0.90
#yabai -m rule --add app="Raycast" sticky=on manage=off
yabai -m rule --add app="Stickies" sticky=off manage=off
ode


echo "yabai configuration loaded.."